title: Neon Vampire
#-------------------------
name: Neon Vampire
#-------------------------
description: Official band site
#-------------------------
author: Neon Vampire
keywords: Neon Vampire, neon vampire, champagne, pop-rock, pop/rock, band, cadiz, san fernando, grupo, musica
#-------------------------
url: https://www.neonvampire.com
#------------contact------
e-mail: neonvampire.official@gmail.com
phone: 687 288469
#-------------------------
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
#-------------------------
permalink: pretty
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', '.bundle', 'extra']
#-------------------------
github_repository: https://github.com/AntonioMateoGomez/neonvampire-site
