title: Champagne
#-------------------------
name: Champagne
#-------------------------
description: Official band site
#-------------------------
author: champagne
keywords: champagne, pop-rock, pop/rock, band, cadiz, san fernando, grupo, musica
#-------------------------
url: https://www.champagnepop.com
#-------------------------
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
#-------------------------
permalink: pretty
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', '.bundle', 'extra']

#-------------------------
github_repository: https://github.com/AntonioMateoGomez/champagnepop-site
